{{- if .Values.namespace.create}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{include "keystone.namespace" .}}
  labels:
    name: {{include "keystone.namespace" .}}
    {{- include "keystone.labels" . | nindent 4}}
---
{{- if .Values.namespace.resourceQuota.enabled}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{include "keystone.fullname" .}}-quota
  namespace: {{include "keystone.namespace" .}}
  labels:
    {{- include "keystone.labels" . | nindent 4}}
spec:
  hard:
    {{- toYaml .Values.namespace.resourceQuota.hard | nindent 4}}
{{- end}}
{{- end}}
